PLATFORM_ROOT_ACCOUNT_ENV_KEY = "platform_root_account"
DATABASE_EXPORT_BUCKET_ENV = "database_export_bucket"

SAMPLE_SECRET_PARAMETER_NAME = "APITemplateSampleSecret"

DATABASE_EXPORT_S3_BUCKET_NAME = "DATABASE_EXPORT_S3_BUCKET_NAME"
