name: lint python
on: 
  push: 
    branches: [ main ]
  pull_request: 
  workflow_dispatch: 

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: cache deps
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('requirements/ci.txt') }}

    - run: python -m ensurepip --upgrade
    - run: pip install --upgrade --upgrade-strategy eager -r requirements/ci.txt || true
    - run: black --check . || true
    - run: isort --check-only --profile black . || true