name: Pipeline (Manual Deploy)

on:
  workflow_dispatch:
    inputs:
      AccountId:
        description: Target AWS Account Id.
        required: true
        type: choice
        options:
          - 316524324729 
          - 590183851380
      Role:
        description: Role name to be assumed by aws-configure action
        default: GithubActionsRole
      Environment:
        description: Deployment environment (dev or prod)
        required: true
        type: choice
        options:
          - development
          - production

jobs:
  deploy_manual:
    name: 🚀 deploy manually
    permissions:
      id-token: write
      contents: read
    uses: BHubAI/shared-workflows/.github/workflows/deploy-python.yml@v1.1.0
    with:
      AccountId: ${{ github.event.inputs.AccountId }}
      Role: ${{ github.event.inputs.Role }}
      BuildEnv: ${{ github.event.inputs.Environment == 'development' && 'dev' || 'prod' }}
      Environment: ${{ github.event.inputs.Environment }}
      PythonVersion: '3.11'